import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import Navbar from "@/components/layout/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className={"globalContainer"}>
          <Header />
          {children}
          <Navbar />
        </main>
        <div className="circles">
          <img className="ellipse" src="/assets/images/ellipse.svg" alt="" />
          <img className="circle1" src="/assets/images/circle1.png" alt="" />
          <img className="circle2" src="/assets/images/circle2.png" alt="" />
          <img className="circle3" src="/assets/images/circle3.png" alt="" />
          <img className="circle4" src="/assets/images/circle4.png" alt="" />
        </div>
      </body>
    </html>
  );
}
